In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn import linear_model

In [ ]:
df=pd.read_csv("housepriceprediction_multplevariable.csv")
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

**Preprocessing the dataset**

In [ ]:
import math
median_bedrooms=math.floor(df.bedrooms.median())
median_bedrooms

3

In [ ]:
df.bedrooms=df.bedrooms.fillna(median_bedrooms)
df

area  bedrooms  age   price
0  2600       3.0   20  550000
1  3000       4.0   15  565000
2  3200       3.0   18  610000
3  3600       3.0   30  595000
4  4000       5.0    8  760000

**Training the model**

In [ ]:
reg=linear_model.LinearRegression()
reg.fit(df[['area','bedrooms','age']],df.price)

LinearRegression()

In [ ]:
reg.coef_ # m1,m2,m3

array([   137.25, -26025.  ,  -6825.  ])

In [ ]:
reg.intercept_ #b

383724.9999999998

**Predicting the value for 3000 sq.ft area,3 bedrooms,40 year old house**

In [ ]:
reg.predict([[3000,3,40]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([444400.])

In [ ]:
# price=m1*area+m2*bedrooms+m3*age+b
137.25*3000-26025.*3-6825.*40+383724.9999999998

444399.9999999998

**Predicting the value for 2500 sq.ft area,4 bedrooms,5 year old house**

In [ ]:
reg.predict([[2500,4,5]])

/usr/local/lib/python3.10/dist-packages/sklearn/base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([588625.])

In [ ]:
# price=m1*area+m2*bedrooms+m3*age+b
137.25*2500-26025.*4-6825.*5+383724.9999999998

588624.9999999998